# Generated by Django 5.1.3 on 2024-11-27 18:32

import albumz.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_cod', models.CharField(default=albumz.models.generate_album_cod, editable=False, max_length=6, unique=True)),
                ('album_nome', models.CharField(max_length=200)),
                ('album_data', models.DateField(verbose_name='date published')),
                ('album_local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografo_nome', models.CharField(max_length=200)),
                ('fotografo_email', models.CharField(max_length=200)),
                ('fotografo_data_nasc', models.DateField(verbose_name='date birth')),
                ('fotografo_data_ingr', models.DateField(verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=albumz.models.foto_upload_path)),
                ('foto_desc', models.CharField(max_length=200)),
                ('foto_data', models.DateField(verbose_name='date published')),
                ('foto_id', models.PositiveIntegerField(editable=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='albumz.album')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumz.fotografo')),
            ],
        ),
    ]
