# Generated by Django 5.1.3 on 2024-11-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_nome', models.CharField(max_length=200)),
                ('album_data', models.DateTimeField(verbose_name='date published')),
                ('album_local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografo_nome', models.CharField(max_length=200)),
                ('fotografo_email', models.CharField(max_length=200)),
                ('fotografo_data_nasc', models.DateTimeField(verbose_name='date birth')),
                ('fotografo_data_ingr', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('foto_desc', models.CharField(max_length=200)),
                ('foto_data', models.DateTimeField(verbose_name='date published')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='albumz.album')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumz.fotografo')),
            ],
        ),
    ]
