# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto_desc',
        ),
    ]
