# Generated by Django 5.1.3 on 2024-11-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumz', '0002_remove_foto_foto_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto_data',
        ),
    ]
