# Generated by Django 5.1.3 on 2024-11-29 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz', '0003_remove_foto_foto_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='edit_permissions',
            field=models.ManyToManyField(related_name='editable_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
