# Generated by Django 5.1.3 on 2024-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumz', '0006_album_album_cover_album_album_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotografo',
        ),
        migrations.AddField(
            model_name='album',
            name='album_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='link',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='senha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='usar_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='usar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
